
import { Info } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

export const TopicsBadge = () => {
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <div>
            <Badge className="flex items-center gap-1 text-xs bg-orange-100 text-orange-800 border-orange-200 hover:bg-orange-200">
              Generated by AI
              <Info className="h-3 w-3" />
            </Badge>
          </div>
        </TooltipTrigger>
        <TooltipContent>
          <p>These topics were identified via AI. Please verify for accuracy before submitting the interaction</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
};
